package app.aaps.core.ui.extensions

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import app.aaps.core.data.ue.Sources
import app.aaps.core.interfaces.userEntry.UserEntryPresentationHelper
import app.aaps.core.ui.compose.navigation.ElementType
import app.aaps.core.ui.compose.navigation.color

@Composable
fun UserEntryPresentationHelper.iconColor(source: Sources): Color = when (source) {
    Sources.Aaps                -> ElementType.AAPS.color()
    Sources.Actions             -> ElementType.TEMP_BASAL.color()
    Sources.Aidex               -> ElementType.CGM_DEX.color()
    Sources.Announcement        -> ElementType.ANNOUNCEMENT.color()
    Sources.Automation          -> ElementType.AUTOMATION.color()
    Sources.Autotune            -> ElementType.AAPS.color()
    Sources.BG                  -> ElementType.CGM_DEX.color()
    Sources.BatteryChange       -> ElementType.BATTERY_CHANGE.color()
    Sources.BgCheck             -> ElementType.BG_CHECK.color()
    Sources.BgFragment          -> ElementType.AAPS.color()
    Sources.CalibrationDialog   -> ElementType.CALIBRATION.color()
    Sources.CarbDialog          -> ElementType.CARBS.color()
    Sources.Combo               -> ElementType.PUMP.color()
    Sources.ConcentrationDialog -> ElementType.INSULIN_MANAGEMENT.color()
    Sources.ConfigBuilder       -> ElementType.CONFIGURATION.color()
    Sources.Dana                -> ElementType.PUMP.color()
    Sources.DanaI               -> ElementType.PUMP.color()
    Sources.DanaR               -> ElementType.PUMP.color()
    Sources.DanaRC              -> ElementType.PUMP.color()
    Sources.DanaRS              -> ElementType.PUMP.color()
    Sources.DanaRv2             -> ElementType.PUMP.color()
    Sources.Database            -> ElementType.AAPS.color()
    Sources.Dexcom              -> ElementType.CGM_DEX.color()
    Sources.DiaconnG8           -> ElementType.PUMP.color()
    Sources.EOPatch2            -> ElementType.PUMP.color()
    Sources.Equil               -> ElementType.PUMP.color()
    Sources.Eversense           -> ElementType.CGM_DEX.color()
    Sources.Exercise            -> ElementType.EXERCISE.color()
    Sources.ExtendedBolusDialog -> ElementType.EXTENDED_BOLUS.color()
    Sources.FillDialog          -> ElementType.FILL.color()
    Sources.Food                -> ElementType.FOOD_MANAGEMENT.color()
    Sources.Garmin              -> ElementType.AAPS.color()
    Sources.Glimp               -> ElementType.CGM_DEX.color()
    Sources.Glunovo             -> ElementType.CGM_DEX.color()
    Sources.Insight             -> ElementType.PUMP.color()
    Sources.Instara             -> ElementType.CGM_DEX.color()
    Sources.Insulin             -> ElementType.INSULIN_MANAGEMENT.color()
    Sources.InsulinDialog       -> ElementType.INSULIN.color()
    Sources.Intelligo           -> ElementType.CGM_DEX.color()
    Sources.LocalProfile        -> ElementType.PROFILE_MANAGEMENT.color()
    Sources.Loop                -> ElementType.LOOP.color()
    Sources.LoopDialog          -> ElementType.LOOP.color()
    Sources.MDI                 -> ElementType.CGM_DEX.color()
    Sources.MM640g              -> ElementType.CGM_DEX.color()
    Sources.Maintenance         -> ElementType.AAPS.color()
    Sources.Medtronic           -> ElementType.PUMP.color()
    Sources.Medtrum             -> ElementType.PUMP.color()
    Sources.NSClient            -> ElementType.AAPS.color()
    Sources.NSClientSource      -> ElementType.AAPS.color()
    Sources.NSProfile           -> ElementType.PROFILE_MANAGEMENT.color()
    Sources.Note                -> ElementType.NOTE.color()
    Sources.NotificationReader  -> ElementType.CGM_DEX.color()
    Sources.Objectives          -> ElementType.AAPS.color()
    Sources.Omnipod             -> ElementType.PUMP.color()
    Sources.OmnipodDash         -> ElementType.PUMP.color()
    Sources.OmnipodEros         -> ElementType.PUMP.color()
    Sources.Ottai               -> ElementType.CGM_DEX.color()
    Sources.Overview            -> ElementType.AAPS.color()
    Sources.PocTech             -> ElementType.CGM_DEX.color()
    Sources.ProfileSwitchDialog -> ElementType.PROFILE_MANAGEMENT.color()
    Sources.Pump                -> ElementType.PUMP.color()
    Sources.Question            -> ElementType.QUESTION.color()
    Sources.QuickWizard         -> ElementType.QUICK_WIZARD.color()
    Sources.Random              -> ElementType.CGM_DEX.color()
    Sources.SMS                 -> ElementType.AAPS.color()
    Sources.Scene               -> ElementType.SCENE_MANAGEMENT.color()
    Sources.SensorInsert        -> ElementType.SENSOR_INSERT.color()
    Sources.SettingsExport      -> ElementType.AAPS.color()
    Sources.SiBionic            -> ElementType.CGM_DEX.color()
    Sources.Sino                -> ElementType.CGM_DEX.color()
    Sources.SiteRotationDialog  -> ElementType.SITE_ROTATION.color()
    Sources.Stats               -> ElementType.STATISTICS.color()
    Sources.SyaiTag             -> ElementType.CGM_DEX.color()
    Sources.TTDialog            -> ElementType.TEMP_TARGET_MANAGEMENT.color()
    Sources.TempBasalDialog     -> ElementType.TEMP_TARGET_MANAGEMENT.color()
    Sources.Tomato              -> ElementType.CGM_DEX.color()
    Sources.TreatmentDialog     -> ElementType.TREATMENT.color()
    Sources.Treatments          -> ElementType.TREATMENTS.color()
    Sources.Unknown             -> ElementType.AAPS.color()
    Sources.VirtualPump         -> ElementType.PUMP.color()
    Sources.Wear                -> ElementType.AAPS.color()
    Sources.WizardDialog        -> ElementType.BOLUS_WIZARD.color()
    Sources.Xdrip               -> ElementType.CGM_XDRIP.color()
}